Linkit/Linkit/Controllers/AssetsController.cs
using Linkit.Data;
using Linkit.Domain;
using Linkit.ViewModel;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.Net.Http.Headers;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace Linkit.Controllers
{
    public class AssetsController : Controller
    {
        private readonly LinkitContext _context;
        private readonly IHostingEnvironment _environment;
        public AssetsController(LinkitContext context, IHostingEnvironment env)
        {
            _context = context;
            _environment = env;
        }

        private List<SelectListItem> PopulateAssetCategories(string[] selectedCategories = null)
        {
            List<SelectListItem> selectListItems = new List<SelectListItem>();
            var dbCategories = _context.AssetCategories.ToList();
            foreach (var item in dbCategories)
            {
                bool selected = selectedCategories == null
                                ? true
                                : selectedCategories.Contains(item.AssetCategoryId.ToString());

                selectListItems.Add(new SelectListItem
                {
                    Selected = selected,
                    Text = item.Code,
                    Value = item.AssetCategoryId.ToString()
                });
            }
            //ViewBag.Categories = selectListItems;
            return selectListItems;

            //new SelectList(_context.AssetCategories.ToList(), "AssetCategoryId", "Code",);
        }

        // GET: Assets
        public IActionResult Index()
        {
            //var linkitContext = _context.Assets.Include(a => a.AssetCategory).Include(a => a.AssetFileType).Include(a => a.AssetType);
            ViewBag.Categories = PopulateAssetCategories();
            return View();
        }

        public async Task<PartialViewResult> List(string[] selectedCategories, string searchString, int? page, int? pageSize)
        {
            var dbAssets = _context.Assets
               .Include(a => a.AssetCategory)
               .Include(a => a.AssetFileType)
               .Include(a => a.AssetType).AsQueryable();

            if (!String.IsNullOrEmpty(searchString))
            {
                dbAssets = dbAssets.Where(c => c.Description.Contains(searchString)
                                     || c.Topic.Contains(searchString)
                                     || c.KeyWords.Contains(searchString));
            }

            if (selectedCategories != null)
            {
                dbAssets = dbAssets.Where(c => c.AssetCategoryId.HasValue == false
                                            || selectedCategories.Contains(c.AssetCategoryId.Value.ToString()));
            }

            PopulateAssetCategories();
            page = page ?? 1;
            pageSize = pageSize ?? 3;
            var assets = await PaginatedList<Asset>.CreateAsync(dbAssets, page.Value, pageSize.Value);

            return PartialView("_List", assets);
        }

        public List<string> GetAllowFileTypes()
        {
            var result = new List<string>();
            string[] fileTypes = _context.AssetFileTypes.Select(c => c.Extensions).ToArray();
            foreach (var item in fileTypes)
            {
                result.AddRange(item.Split(','));
            }
            return result;
        }

        private bool IsValidFileType(string fileType)
        {
            return GetAllowFileTypes().Contains(fileType);
        }


        public IActionResult HelpResourceUpload(int? id)
        {
            ResourceViewModel viewModel = new ResourceViewModel()
            {
                AvailiableCategories = new SelectList(_context.AssetCategories, "AssetCategoryId", "Code"),
                RadioHelpResourceLinkOrFile = "link"
            };

            viewModel.AllowFileTypes = GetAllowFileTypes();

            if (id.HasValue)
            {
                var asset = _context.Assets.Include(c => c.AssetCategory)
                                    .Include(c => c.AssetType)
                                    .Include(c => c.AssetFileType)
                                    .FirstOrDefault(c => c.AssetId == id.Value);
                viewModel.AssetCategoryId = asset.AssetCategoryId;
                viewModel.AssetFilePath = asset.AssetFilePath;
                viewModel.AssetId = asset.AssetId;
                viewModel.AssetLink = asset.AssetLink;
                viewModel.Description = asset.Description;
                viewModel.KeyWords = asset.KeyWords;
                viewModel.Topic = asset.Topic;

                viewModel.AvailiableCategories = new SelectList(_context.AssetCategories, "AssetCategoryId", "Code", asset.AssetCategory);
            }

            viewModel.RadioHelpResourceLinkOrFile = string.IsNullOrEmpty(viewModel.AssetFilePath) ? "link" : "file";
            return View(viewModel);
        }


        [HttpPost]
        public async Task<IActionResult> HelpResourceUpload(ResourceViewModel viewModel, IFormFile AssetFiles)
        {
            #region upload file
            string filePath = "";
            if (viewModel.RadioHelpResourceLinkOrFile == "file")
            {
                filePath = ContentDispositionHeaderValue.Parse(AssetFiles.ContentDisposition).FileName.Trim('"');
                filePath = Path.Combine(_environment.WebRootPath, "upload") + $@"\{filePath}";
                string extention = Path.GetExtension(filePath).Remove(0,1).ToLower();
                if (IsValidFileType(extention) == false)
                {
                    ModelState.AddModelError("", "Forbidden file type");
                    ViewBag.UploadError = "Forbidden file type";
                    return View(viewModel);
                }

                if (AssetFiles.Length > 0)
                {
                    using (var stream = new FileStream(filePath, FileMode.Create))
                    {
                        await AssetFiles.CopyToAsync(stream);
                    }
                }
                viewModel.AssetFilePath = filePath;
                viewModel.AssetFiles = "valid";
            }
            #endregion

            if (TryValidateModel(viewModel))
            {
                CreateOrUpdateAsset(viewModel);
                return RedirectToAction("Index");
            }

            viewModel.AvailiableCategories = new SelectList(_context.AssetCategories, "AssetCategoryId", "Code");
            viewModel.RadioHelpResourceLinkOrFile = "link";
            return View(viewModel);
        }

        private void CreateOrUpdateAsset(ResourceViewModel viewModel)
        {
            if (viewModel.AssetId == 0)
            {
                Asset asset = new Asset()
                {
                    AssetCategoryId = viewModel.AssetCategoryId,
                    Topic = viewModel.Topic,
                    Description = viewModel.Description,
                    KeyWords = viewModel.KeyWords,
                    AssetLink = viewModel.AssetLink,
                    DateCreated = DateTime.Now,
                    DateUpdated = DateTime.Now,
                    AssetFilePath = viewModel.AssetFilePath
                };
                _context.Assets.Add(asset);
            }
            else
            {
                var dbAsset = _context.Assets.Include(c => c.AssetCategory)
                             .Include(c => c.AssetType)
                             .Include(c => c.AssetFileType)
                             .FirstOrDefault(c => c.AssetId == viewModel.AssetId);
                dbAsset.AssetCategoryId = viewModel.AssetCategoryId;
                dbAsset.AssetFilePath = viewModel.AssetFilePath;
                dbAsset.AssetId = viewModel.AssetId;
                dbAsset.AssetLink = viewModel.AssetLink;
                dbAsset.Description = viewModel.Description;
                dbAsset.KeyWords = viewModel.KeyWords;
                dbAsset.Topic = viewModel.Topic;
                dbAsset.AssetFilePath = viewModel.AssetFilePath;
            }
            _context.SaveChanges();
        }

        // GET: Assets/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var asset = await _context.Assets
                .Include(a => a.AssetCategory)
                .Include(a => a.AssetFileType)
                .Include(a => a.AssetType)
                .SingleOrDefaultAsync(m => m.AssetId == id);
            if (asset == null)
            {
                return NotFound();
            }

            return View(asset);
        }

        // GET: Assets/Create
        public IActionResult Create()
        {
            ViewData["AssetCategoryId"] = new SelectList(_context.AssetCategories, "AssetCategoryId", "AssetCategoryId");
            ViewData["AssetFileTypeId"] = new SelectList(_context.AssetFileTypes, "AssetFileTypeId", "Name");
            ViewData["AssetTypeId"] = new SelectList(_context.AssetTypes, "AssetTypeId", "AssetTypeId");
            return View();
        }

        // POST: Assets/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("AssetId,AssetTypeId,AssetCategoryId,AssetFileTypeId,Topic,Description,DateUpdated,DateCreated,KeyWords,AssetFilePath,AssetLink")] Asset asset)
        {
            if (ModelState.IsValid)
            {
                _context.Add(asset);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index");

Linkit/Linkit/Views/Shared/Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Linkit</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Linkit</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                </ul>
                @await Html.PartialAsync("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2016 - Linkit</p>
        </footer>
    </div>

    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("scripts", required: false)
</body>
</html>

Linkit/Linkit/Views/Shared/_Layout.cshtml
@inject Microsoft.ApplicationInsights.AspNetCore.JavaScriptSnippet JavaScriptSnippet
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Linkit</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.5.0/css/font-awesome.min.css">
        <link href="~/css/AdminLTE.css" rel="stylesheet" />
        <link rel="stylesheet" href="~/css/site.css" />

        <link href="~/css/skins/_all-skins.css" rel="stylesheet" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>

    <script type="text/javascript">
        var Linkit = Linkit || {};
        Linkit.Urls = Linkit.Urls || {};
        Linkit.Urls.BaseUrl = '@Url.Content("~")';
        Linkit.Urls.GetAssetsListUrl = '@Url.Action("List", "Assets")';
    </script>
    @Html.Raw(JavaScriptSnippet.FullScript)
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Linkit</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Assets" asp-action="Index">Assets</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                </ul>
            </div>
        </div>
    </nav>
    @*<div class="container body-content">
        style="margin-left: 5%; margin-right: 5%"*@
    <div class="wrapper">
        <div class="content-wrapper" style="margin-left:5%; margin-right:5%">
            @RenderBody()
        </div>

        <hr />
        <footer>
            <p>&copy; 2017 - Linkit</p>
        </footer>
    </div>

    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
        <script src="~/lib/jquery-validation/dist/additional-methods.js"></script>
        <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
        <script src="~/js/plugins/slimScroll/jquery.slimscroll.js"></script>

        <script src="~/js/spin.js"></script>

        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/app.js"></script>
        <script src="~/js/demo.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
        <script src="~/js/linkit.js"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>